In [55]:
print("Hello")

Hello


In [56]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [57]:
df = pd.read_csv('../data_set/Linear_regression_placement.csv')

In [58]:
df.head()
df.isnull().sum()

cgpa       0
package    0
dtype: int64

In [59]:
plt.scatter(df['cgpa'],df['package'])
plt.xlabel('CGPA')
plt.ylabel('Package in LPA')
plt.show()

In [60]:

import sklearn

In [61]:
x = df.iloc[:,0:1]
y = df['package']

In [62]:
print(type(x))

<class 'pandas.core.frame.DataFrame'>


In [63]:
print(type(y))

<class 'pandas.core.series.Series'>


In [64]:
from sklearn.model_selection import train_test_split

In [65]:
x_train , x_test , y_train, y_test = train_test_split(x,y,test_size=0.2)

In [66]:
from sklearn.linear_model import LinearRegression

In [67]:
model = LinearRegression()


In [68]:
model.fit(x_train,y_train)

LinearRegression()

In [69]:
y_pred = model.predict(x_test)
y_pred = y_pred.round(2)

In [70]:
model.predict(np.array([9.5]).reshape(1,1))

d:\ML_algos\ml_algo-env\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([4.45397691])

In [71]:
from sklearn.metrics import accuracy_score

In [72]:
y_test

92     4.00
122    2.01
88     1.48
107    2.59
50     4.43
4      3.57
160    2.93
13     2.89
1      1.98
184    3.14
158    3.04
67     2.89
181    3.89
99     3.24
196    2.57
22     2.30
170    2.87
40     4.02
125    3.16
2      3.25
47     3.26
58     3.09
119    2.65
14     3.42
139    2.40
152    3.08
20     3.16
154    2.85
46     2.26
174    2.99
18     2.98
33     2.73
85     1.48
17     2.09
59     3.31
112    4.10
42     2.54
36     2.84
25     3.65
178    3.63
Name: package, dtype: float64

In [73]:
y_pred

array([3.52, 1.89, 1.66, 2.6 , 4.5 , 2.96, 3.07, 2.95, 1.89, 3.51, 2.38,
       2.7 , 3.7 , 2.76, 2.34, 2.49, 2.53, 4.38, 3.18, 3.47, 2.31, 2.94,
       3.22, 3.42, 3.1 , 3.21, 3.15, 3.04, 2.45, 3.18, 2.96, 2.61, 1.7 ,
       2.04, 3.32, 3.92, 2.38, 2.4 , 3.15, 3.66])

In [74]:
data_point = x_train.iloc[0].values.reshape(1,1)
model.predict(data_point)

d:\ML_algos\ml_algo-env\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([3.44164719])

In [76]:
# Let us visualize the line that it has drawn

In [81]:
plt.scatter(df['cgpa'],df['package'])
plt.plot(x_train,model.predict(x_train),color = 'red')
plt.xlabel('cgpa')
plt.ylabel('package in the cgpa')

Text(0, 0.5, 'package in the cgpa')

In [83]:
# coef means the coefficient of the x which is the slope value
model.coef_

array([0.58516169])

In [84]:
model.intercept_

np.float64(-1.105059125758916)

In [ ]:
# equation of the line y = mx + b
new_package = 0.58516169*data_point - 1.105059125758916 