In [36]:
print("Hello")

Hello


In [37]:
from sklearn.datasets import load_diabetes
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
from sklearn.model_selection import train_test_split

In [38]:
X , y = load_diabetes(return_X_y=True)

In [39]:
X.shape

(442, 10)

In [40]:
x_train , x_test , y_train , y_test = train_test_split(X,y,test_size=0.2 , random_state=2)

In [41]:
reg = LinearRegression()


In [42]:
reg.fit(x_train,y_train)

LinearRegression()

In [43]:
reg.coef_

array([  -9.15865318, -205.45432163,  516.69374454,  340.61999905,
       -895.5520019 ,  561.22067904,  153.89310954,  126.73139688,
        861.12700152,   52.42112238])

In [44]:
reg.intercept_

np.float64(151.88331005254167)

In [45]:
y_pred = reg.predict(x_test)

In [46]:
r2_score(y_test,y_pred)

0.4399338661568969

# Lets do the custom implementation using GD regression

In [47]:
import numpy as np

In [ ]:
class GDRegressor:
    def __init__(self,epochs = 100 , learning_rate = 0.01,intercept = 0):
        self.coef = None 
        self.epochs = epochs
        self.learning_rate = learning_rate
        self.intercept = intercept
    
    
    def calculate_loss(self,x,y,curr_column):
        n = x.shape[0]
        
        if curr_column == 0 :
            return (-2/n)*np.sum(y-np.dot(x,np.transpose(self.coef)))
        
        return (-2/n)*np.sum((y-np.dot(x,np.transpose(self.coef))*x[:,curr_column].ravel()))
        
    
    def fit(self,x_train , y_train):
        m = x_train.shape[1] + 1
        n = x_train.shape[0]                                           
        
        x_train = np.hstack((np.ones(n).reshape(n,1),x_train))
        self.coef = np.ones(m)
        
        self.coef[0] = 0 
        
            
        for i in range(self.epochs) :
            for j in range(x_train.shape[1]):
                self.coef[j] = self.coef[j] - self.learning_rate*(self.calculate_loss(x_train,y_train,j))
                print("j" , "  " , self.coef[j])
            
            self.intercept = self.coef[0]
    
    def predict(self,x_test):
        n = x_test.shape[0]
        return np.dot(np.hstack((np.ones(n).reshape(n,1),x_test)),np.transpose(self.coef))


In [49]:
gd_reg = GDRegressor()

In [50]:
gd_reg.fit(x_train,y_train)

(353, 11)
(353, 11)


ValueError: operands could not be broadcast together with shapes (353,) (11,) 

In [ ]:
gd_reg.coef

array([150.46744507,   1.        ,   1.        ,   1.        ,
         1.        ,   1.        ,   1.        ,   1.        ,
         1.        ,   1.        ,   1.        ])

In [ ]:
gd_reg.intercept

np.float64(150.4674450654641)

In [ ]:
y_pred = gd_reg.predict(x_test)

In [ ]:
y_pred

array([150.65993029, 150.76863383, 150.50593254, 150.31581595,
       150.81458915, 150.6738518 , 150.18328389, 150.14929759,
       150.20217243, 150.60463151, 150.79758805, 150.46937964,
       150.63161843, 150.64202227, 150.71903649, 150.43792562,
       150.46569352, 150.20409581, 150.48691074, 150.44257323,
       150.16304867, 150.99614708, 150.63232776, 150.75668288,
       150.42052709, 150.71421518, 150.70919517, 150.62798361,
       150.02173936, 151.10135132, 150.84992416, 150.31870735,
       150.00822384, 150.39669985, 150.7074678 , 150.49461356,
       150.69047249, 150.77231336, 150.31925947, 150.86430771,
       150.32836417, 150.41771136, 150.62019812, 150.60274428,
       150.50439374, 150.34855655, 150.62869028, 150.93316197,
       150.35127605, 150.95036969, 150.85429454, 150.1221765 ,
       150.25211493, 150.6201871 , 150.7210986 , 150.36283327,
       150.76291188, 150.25198764, 150.53048029, 150.23274321,
       150.55481585, 150.69984937, 150.42342418, 150.57

In [ ]:
r2_score(y_test,y_pred
         )

-0.009494013323033457